import "@/styles/globals.css";
import cn from "@/utils/cn";

import { Poppins } from "next/font/google";
import MainLayout from "@/components/MainLayout";

// primary font
const poppins = Poppins({
  variable: "--font-primary",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Dua App",
  description: "Generated by Next JS",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn(poppins.variable, "bg-[#ebeef2] font-primary")}>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
